---
version: "3.7"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    #network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - UMASK_SET=022 #optional
    ports:
      - 32400:32400
      - 3005:3005/udp
      - 32469:32469
      - 32469:32469/udp
      - 1900:1900/udp
    volumes:
      - ${PARENT_DIR}:/plex
      - ${PARENT_DIR}/plex/config:/plex/config
      - ${PARENT_DIR}/tvseries:/plex/tv
      - ${PARENT_DIR}/movies:/plex/movies
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - UMASK_SET=022 #optional
    volumes:
      - ${PARENT_DIR}:/plex
      - ${PARENT_DIR}/radarr/config:/plex/config
      - ${PARENT_DIR}/movies:/plex/movies
      - ${PARENT_DIR}/downloads:/plex/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ${PARENT_DIR}:/plex
      - ${PARENT_DIR}/sonarr/config:/plex/config
      - ${PARENT_DIR}/downloads:/plex/downloads
      - ${PARENT_DIR}/tvseries:/plex/tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    ports:
      - 8989:8989
    restart: always

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${PARENT_DIR}/jackett/downloads:/downloads
      - ${PARENT_DIR}/pool/jackett/config:/config
    ports:
      - 9117:9117
    restart: always

  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    network_mode: bridge
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_USERNAME=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASS}
      - WEBPROXY_ENABLED=false
      - PUID=1000
      - PGID=1000
      - LOCAL_NETWORK=192.168.0.0/24
    volumes:
      - ${PARENT_DIR}/transmission/config:/config
      - ${PARENT_DIR}/downloads:/data
    ports:
      - 9091:9091
    restart: always
