---
version: "3.7"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    #network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - UMASK_SET=022 #optional
    ports:
      - 32400:32400
      - 3005:3005/udp
      - 32469:32469
      - 32469:32469/udp
      - 1900:1900/udp
    volumes:
      - ./library:/config
      - ./tvseries:/tv
      - ./movies:/movies
    restart: unless-stopped
    
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=022 #optional
    volumes:
      - ./data:/config
      - ./movies:/movies
      - ./downloadclient-downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
